# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nb_dev_test',
                'doc_host': 'https://MithasKumar.github.io',
                'git_url': 'https://github.com/MithasKumar/nb_dev_test',
                'lib_path': 'nb_dev_test'},
  'syms': { 'nb_dev_test.core': { 'nb_dev_test.core.add': ('core.html#add', 'nb_dev_test/core.py'),
                                  'nb_dev_test.core.foo': ('core.html#foo', 'nb_dev_test/core.py')},
            'nb_dev_test.secound_module': {'nb_dev_test.secound_module.sub': ('second_module.html#sub', 'nb_dev_test/secound_module.py')}}}
