# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_second_module.ipynb.

# %% auto 0
__all__ = ['sub']

# %% ../nbs/02_second_module.ipynb 2
def sub(a:int, b:int):
    '''
    Function to subtracts two numbers
    '''
    print(f'a - b = {a-b}')
